### ISSUE TITLE
Graphs disappearing when importing aurora

### ISSUE THREAD

**Issue by ndm1019** [fsciortino/Aurora#113]
I am trying to use Aurora to produce a spectrum for argon by following #45, but I can't get the graph to display at the end. I thought it was the version of matplotlib I was using (suggested in #108), but it persisted using 3.5.0, 3.5.3, and 3.9.2. I am running the scripts in a conda environment with python 3.11.10. 

As a sanity check I tried running the simplest script possible: 
import matplotlib.pyplot as plt
import numpy as np
x = np.linspace(0,100,100)
y = np.linspace(0,100,100)
plt.plot(x,y)
plt.show()

which worked fine. Adding "import aurora" or importing any individual function from Aurora results in the graph not showing up. I can use plt.savefig() to save the output, so I know the graph is at least being generated, but this makes it difficult to zoom in on regions of interest. Any insight would be greatly appreciated!

**Comment by odstrcilt** [comment]
Could you try to run plt.ioff() after importing Aurora?

**Comment by ndm1019** [comment]
This has fixed the issue! Thank you.
