### ISSUE TITLE
Paths for downloading data from openadas seem to be out of date in some cases

### ISSUE THREAD

**Issue by eldond** [fsciortino/Aurora#90]
I was attempting
`aurora.atomic.get_atom_data('C', ['pls'])`, which failed because it attempted to download `https://open.adas.ac.uk/download/adf11//pls/pls_C_14.dat`, which doesn't exist. I looked up PLS for carbon manually at open.adas.ac.uk and found that the filename is `pls96_c.dat`.

I changed
```
files["C"]["pls"] = "pls_C_14.dat"
```
to
```
files["C"]["pls"] = "pls96_c.dat"
```
on line 229 of `adas_files.py` and then `aurora.atomic.get_atom_data('C', **['pls'])` completed without an error.

**Comment by odstrcilt** [comment]
Some files can be found by setting the variable 
`AURORA_ADAS_DIR` to `/fusion/projects/omfit-results/aurora_dir/ `

pls are SXR filtered radiation files, which are specific for every diagnostic.  Number 14 is for DIII-D SXR diagnostic with 127um Be filter and number 15 is for 12.7um Be filter. These files are located here
` /fusion/projects/codes/strahl/public/atomdat/newdat/`

I guess, pls96_c.dat is a file from JET, which had 250 and 350um Be filters. They cannot be used on DIII-D. 

IMPRAD  should load the files from the right location.

**Comment by eldond** [comment]
Yes, if I run on iris, it does work properly. When I tried running on my laptop, it didn't work because I didn't have a copy of the files. Maybe an error message could explain limitations of openadas that you just mentioned?

**Comment by odstrcilt** [comment]
I have tried to make the error message a bit more useful
https://github.com/fsciortino/Aurora/pull/92
