### ISSUE TITLE
erh5.dat file from degas2 was deleted from web

### ISSUE THREAD

**Issue by odstrcilt** [fsciortino/Aurora#95]
The file loaded by neutral.py is not there anymore. 
https://github.com/fsciortino/Aurora/blob/f20a9c085edf378d5d860df4aa1c0fb158ae09bd/aurora/neutrals.py#L52

@fsciortino do you have a copy of this file somewhere?

**Comment by fsciortino** [comment]
@odstrcilt I do not, unfortunately. I would suggest emailing Daren Stotler to ask for it, requesting permission to upload the file somewhere (either in Aurora or elsewhere).

https://theory.pppl.gov/people/profile.php?pid=11&n=Daren-Stotler
